platform :ios, '11.0'

    target 'Escort Client' do
      use_frameworks!
      pod 'GoogleMaps', '~> 2.6.0'
      pod 'PusherSwift', '~> 5.1.1'
      pod 'Alamofire', '~> 4.6.0'
      pod 'GooglePlaces'
    end